export const metadata = {
  title: "Cash on Cash Return Calculator | Real Estate Investment Analysis",
  description:
    "Calculate cash on cash return for rental properties, Airbnb investments, annual cash flow, cash invested, ROI, cap rate, and real estate profitability.",
};

export default function CashOnCashReturnCalculatorPage() {
  return (
    <main style={{ maxWidth: "1100px", margin: "0 auto", padding: "80px 24px" }}>
      <h1 style={{ fontSize: "64px", fontWeight: "700", marginBottom: "24px" }}>
        Cash on Cash Return Calculator
      </h1>

      <p style={{ fontSize: "24px", lineHeight: "1.6", marginBottom: "48px" }}>
        Calculate cash on cash return, annual cash flow, total cash invested,
        ROI, cap rate, and rental property investment performance before buying
        your next real estate deal.
      </p>

      <a
        href="/signup"
        style={{
          display: "inline-block",
          background: "#2563eb",
          color: "#ffffff",
          padding: "16px 28px",
          borderRadius: "12px",
          textDecoration: "none",
          fontWeight: "700",
          fontSize: "18px",
          marginBottom: "48px",
        }}
      >
        Calculate Cash Return Free
      </a>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
          gap: "24px",
          marginBottom: "64px",
        }}
      >
        <div style={{ border: "1px solid #e5e7eb", borderRadius: "16px", padding: "24px" }}>
          <h3>Cash Return Analysis</h3>
          <p>Measure annual cash flow compared with total cash invested.</p>
        </div>

        <div style={{ border: "1px solid #e5e7eb", borderRadius: "16px", padding: "24px" }}>
          <h3>Rental Property ROI</h3>
          <p>Compare investor returns across rental and Airbnb properties.</p>
        </div>

        <div style={{ border: "1px solid #e5e7eb", borderRadius: "16px", padding: "24px" }}>
          <h3>Investment Comparison</h3>
          <p>Evaluate deals using cash flow, cap rate, NOI, and ROI.</p>
        </div>
      </div>

      <section style={{ marginBottom: "64px" }}>
        <h2 style={{ fontSize: "48px", marginBottom: "24px" }}>
          What Is Cash on Cash Return?
        </h2>

        <p style={{ fontSize: "22px", lineHeight: "1.8" }}>
          Cash on cash return measures the annual cash income generated by a real
          estate investment compared with the actual cash invested. It is one of
          the most useful metrics for investors who use financing.
        </p>
      </section>

      <section style={{ marginBottom: "64px" }}>
        <h2 style={{ fontSize: "48px", marginBottom: "24px" }}>
          How to Calculate Cash on Cash Return
        </h2>

        <p style={{ fontSize: "22px", lineHeight: "1.8", marginBottom: "24px" }}>
          Cash on cash return is calculated by dividing annual pre-tax cash flow
          by total cash invested, then multiplying by 100.
        </p>

        <div
          style={{
            background: "#f3f4f6",
            padding: "24px",
            borderRadius: "12px",
            fontSize: "24px",
            fontWeight: "700",
            marginBottom: "24px",
          }}
        >
          Cash on Cash Return = Annual Cash Flow ÷ Total Cash Invested × 100
        </div>

        <p style={{ fontSize: "22px", lineHeight: "1.8" }}>
          Total cash invested may include down payment, closing costs, repair
          costs, furnishing costs, startup expenses, and other upfront investment
          costs.
        </p>
      </section>

      <section style={{ marginBottom: "64px" }}>
        <h2 style={{ fontSize: "48px", marginBottom: "24px" }}>
          Why Cash on Cash Return Matters
        </h2>

        <p style={{ fontSize: "22px", lineHeight: "1.8" }}>
          Cash on cash return helps investors understand how efficiently their
          invested cash is generating income. A property may have a strong cap
          rate but a weaker cash on cash return if financing costs are high or
          the required upfront investment is large.
        </p>
      </section>

      <section style={{ marginBottom: "64px" }}>
        <h2 style={{ fontSize: "48px", marginBottom: "24px" }}>
          Cash on Cash Return for Airbnb Investments
        </h2>

        <p style={{ fontSize: "22px", lineHeight: "1.8", marginBottom: "24px" }}>
          Airbnb and short-term rental investors use cash on cash return to
          evaluate how much annual cash flow a property may generate compared
          with cash invested for down payment, furniture, setup, and operating
          reserves.
        </p>

        <p style={{ fontSize: "22px", lineHeight: "1.8" }}>
          Because Airbnb income can change with seasonality, occupancy, and
          nightly rates, investors should compare cash on cash return together
          with cap rate, NOI, expenses, and break-even occupancy.
        </p>
      </section>

      <section style={{ marginBottom: "64px" }}>
        <h2 style={{ fontSize: "48px", marginBottom: "24px" }}>
          Cash on Cash Return Calculator FAQ
        </h2>

        <h3>Is cash on cash return the same as ROI?</h3>
        <p style={{ fontSize: "22px", lineHeight: "1.8" }}>
          Not exactly. Cash on cash return focuses on annual cash flow compared
          with actual cash invested, while ROI can include broader investment
          performance.
        </p>

        <h3 style={{ marginTop: "24px" }}>
          What is a good cash on cash return?
        </h3>
        <p style={{ fontSize: "22px", lineHeight: "1.8" }}>
          A good cash on cash return depends on the market, financing structure,
          property type, and risk level. Investors usually compare similar
          properties using the same assumptions.
        </p>

        <h3 style={{ marginTop: "24px" }}>
          Does cash on cash return include mortgage payments?
        </h3>
        <p style={{ fontSize: "22px", lineHeight: "1.8" }}>
          Yes. Cash on cash return usually uses cash flow after debt service,
          which means mortgage payments are included in the calculation.
        </p>

        <h3 style={{ marginTop: "24px" }}>
          Can Airbnb investors use cash on cash return?
        </h3>
        <p style={{ fontSize: "22px", lineHeight: "1.8" }}>
          Yes. It is useful for Airbnb investors because it shows how efficiently
          invested cash may generate annual returns.
        </p>
      </section>

      <section>
        <h2 style={{ fontSize: "48px", marginBottom: "24px" }}>
          Start Analyzing Cash Returns
        </h2>

        <p style={{ fontSize: "22px", lineHeight: "1.8", marginBottom: "24px" }}>
          HostMetricsPro helps investors analyze cash on cash return, cash flow,
          cap rate, NOI, ROI, Airbnb revenue, occupancy, expenses, and overall
          real estate investment quality.
        </p>

        <a
          href="/signup"
          style={{
            display: "inline-block",
            background: "#111827",
            color: "#ffffff",
            padding: "16px 28px",
            borderRadius: "12px",
            textDecoration: "none",
            fontWeight: "700",
          }}
        >
          Try HostMetricsPro Free
        </a>
      </section>
    </main>
  );
}